services:
  mlflow:
    build:
      context: .
      args:
        PYTHON_VERSION: "3.12"
        MLFLOW_VERSION: "3.1.2"
        EXTRA_PIP_PACKAGES: "psycopg2-binary==2.9.10"
    command: [
      "--host", "0.0.0.0",
      "--port", "5000",
      "--backend-store-uri", "postgresql+psycopg2://admin:password@postgres/mlflow",
      "--default-artifact-root", "file:/./mlruns",
    ]
    ports:
      - "5003:5000"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mlflow
    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -U admin -d mlflow"
      ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s