name: Helm Lint

on:
  push:
    paths:
      - 'chart/**'
      - '.github/workflows/helm.yml'
  pull_request:
    paths:
      - 'chart/**'
      - '.github/workflows/helm.yml'

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Lint Helm chart
        run: helm lint chart/
